import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import { sanityClient } from "../lib/sanity";

const inter = Inter({ subsets: ["latin"] });

export async function getStaticProps() {
  const query = `*[_type == "home"][0]{
    title,
    subtitle,
    "mainImage": mainImage.asset->url,
  }`;

  const data = await sanityClient.fetch(query);
  console.log(data);
  return {
    props: { data },
  };
}

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <h1>{data.title}</h1>
          <h2>{data.subtitle}</h2>
          <Image
            src={data.mainImage}
            alt="Banner Image"
            width={800}
            height={400}
          />
        </div>
      </main>
    </>
  );
}
